Enhancement: Choose Card Types to Create from Command Palette
tillywork/tillywork pull request #103
Opened 2024-06-26 17:40 UTC by codonade

Resolves #99

2024-06-26 17:59 UTC, MoShizzle requested changes

2024-06-26 17:59 UTC, MoShizzle commented on packages/frontend/src/composables/useCommands.ts
> +              section: 'Card',
Each card type should have it's own section

2024-06-26 17:59 UTC, MoShizzle commented on packages/frontend/src/composables/useCommands.ts
>        {
Remove the default command

2024-06-27 07:13 UTC, codonade commented on packages/frontend/src/composables/useCommands.ts
> +              section: 'Card',
Sorry, thought you meant separate commands - not sections. I'll do this right now.

2024-07-01 08:51 UTC, MoShizzle approved these changes

2024-07-01 08:51 UTC, merged