Ability to set icon of space/list
tillywork/tillywork pull request #133
Opened 2024-07-08 05:13 UTC by Us3r-gitHub

Closes #125

2024-07-09 10:53 UTC, MoShizzle requested changes
We should also be able to select icon color with BaseColorPicker along with the icon, for both lists and spaces

2024-07-09 10:53 UTC, MoShizzle commented on packages/backend/src/migrations/1720414956770-add-icon-column-to-space-and-list-tables.ts
> +    isNullable: true,
Remove isNullable and set `mdi-list-box-outline` for lists and `mdi-folder-outline` for spaces as default

2024-07-10 00:01 UTC, Us3r-gitHub commented on packages/backend/src/migrations/1720414956770-add-icon-column-to-space-and-list-tables.ts
> +    isNullable: true,
Should it be define in migration?
Or in entity file?

2024-07-10 06:11 UTC, Us3r-gitHub commented on packages/backend/src/migrations/1720414956770-add-icon-column-to-space-and-list-tables.ts
> +    isNullable: true,
Added on [93102bc](https://github.com/tillywork/tillywork/pull/133/commits/93102bc6f4c908c7b545fc7364da6fa3634418bb)

2024-07-14 09:00 UTC, MoShizzle approved these changes

2024-07-14 09:00 UTC, merged