feat(view): Handle Quick Filter
tillywork/tillywork pull request #143
Opened 2024-07-12 06:25 UTC by Us3r-gitHub

Closes #127

2024-07-13 09:59 UTC, Us3r-gitHub commented
I've set up quick filters for the Date, Assignee, and Stage sections, but I'm still unsure about how to implement the Dropdown and Label. Could you provide more detailed explanations on those?

2024-07-14 08:57 UTC, MoShizzle commented
For dropdowns and labels let's implement that part next week, I'm releasing a change that lets the user assign custom fields to lists and entities, so we'll be getting them through that instead of the current workspace.

To answer your question though, you can get the fields through field table with type of `label` or `dropdown`, and the `items` column contains the dropdown or label options as an array of objects, where the `items[0].item` is the value of the filter.

2024-07-14 09:45 UTC, MoShizzle commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
What does this do?

2024-07-15 02:03 UTC, Us3r-gitHub commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
As commit's title [e833694](https://github.com/tillywork/tillywork/pull/143/commits/e8336946d38851bc2245e7f58f49a5259e091cab)

We need to use dynamic values instead of hardcoded ones. Currently, I generate a random number for this purpose. Alternatively, we could allow the function caller to set its value.

Do you have any other suggestions for how to handle this?

2024-07-15 02:07 UTC, Us3r-gitHub commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
The current issue arises when multiple `between` conditions are given, which can potentially introduce bugs.

For example, 
![image](https://github.com/user-attachments/assets/0860162e-deed-4af2-a4fd-46cc1d7e060f)

2024-07-15 08:35 UTC, MoShizzle commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
Ah, I see the issue, I think we can simply solve it by not using placeholders in the query and injecting the values directly, e.g `${fieldName} ${betweenOperator} ${processedValue[0]} AND ${processedValue[1]}`

2024-07-15 10:18 UTC, Us3r-gitHub commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
I think it may be unsafe and could potentially lead to security issues.

2024-07-15 12:27 UTC, MoShizzle commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
Maybe something like this?
`queryBuilder.andWhere(new Brackets(qb => {
  qb.where(`${fieldName} BETWEEN :lower AND :upper`, {
    lower: processedValue[0],
    upper: processedValue[1]
  });
}));`

Which should make each condition scoped, and fix the conflicts between the values

2024-07-15 23:20 UTC, Us3r-gitHub commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
I've tried your solution, but it hasn't resolved the problem; conflicts still persist.

2024-07-15 23:28 UTC, Us3r-gitHub commented on packages/backend/src/app/common/helpers/query.builder.helper.ts
> +                const randomNumber1 = this.getRandomInt();
It seems the same parameter will be used within one query, whether it's conditionally scoped or not.

2024-07-18 08:56 UTC, MoShizzle requested changes

2024-07-18 08:56 UTC, MoShizzle commented on packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilter.vue
> +        const group = type as QuickFilterGroup;
To make it clearer for the user, the group should be the field name, if I have a dropdown field called Priority for example, it should not show as Dropdown -> Priority, it should just be a group called Priority with the options along side it.

2024-07-18 09:04 UTC, Us3r-gitHub commented on packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilter.vue
> +        const group = type as QuickFilterGroup;
So, should we bring it up to the root level, like the others (due date, assignee, stage)?

2024-07-18 09:18 UTC, MoShizzle commented on packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilter.vue
> +        const group = type as QuickFilterGroup;
Yes exactly!

2024-07-19 01:10 UTC, Us3r-gitHub commented on packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilter.vue
> +        const group = type as QuickFilterGroup;
![image](https://github.com/user-attachments/assets/878260e6-ab61-4b48-aeaa-5a786b26aa0e)
I've updated it and it now looks like the screenshot.

Do you think it needs to be reordered? (Custom Fields should be last.)
I'm curious why 'stage' is at the end. Previously, I thought it was ordered alphabetically, but it seems that's not the case.

2024-07-19 08:49 UTC, codonade commented on packages/frontend/src/components/project-management/views/BaseViewChipFilter/BaseViewChipFilter.vue
> +        const group = type as QuickFilterGroup;
> (Custom Fields should be last.)

Yeah I agree with this. I think it makes more sense.

2024-07-19 22:47 UTC, Us3r-gitHub commented
![image](https://github.com/user-attachments/assets/276f9d61-7061-4b37-b0ff-0e7bc4f3c060)
I'd like to discuss the display of filters. Currently, combining quick and advanced filters can clutter the interface, especially with numerous custom fields.
What if we split them into two separate modes for display purposes? This change would only affect how filters are presented visually; the underlying values would still be combined from both modes.

Instead of a button labeled '+ Advanced Filter,' we could use 'Switch to Advanced Filter'

2024-07-20 06:42 UTC, codonade commented
> Instead of a button labeled '+ Advanced Filter,' we could use 'Switch to Advanced Filter'

Again, I pretty much agree with you.

2024-07-20 08:36 UTC, MoShizzle approved these changes

2024-07-20 08:36 UTC, merged