Feat: Search Bar in User Selector
tillywork/tillywork pull request #60
Opened 2024-05-30 12:17 UTC by codonade

Search for a specific user when selecting one through the `<base-user-selector />` component. Fixes #45

2024-05-30 16:24 UTC, MoShizzle requested changes
Added some comments, also see if we can also search by email, not just the user's name (not a priority at this point)

2024-05-30 16:24 UTC, MoShizzle commented on packages/frontend/src/components/common/users/types.ts
> +export function getUserFullName(user: User): string {
Move this to users service, types.ts files should only contain types, without functionality.

2024-05-30 16:24 UTC, MoShizzle commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +          v-for="user in users.filter(
The users.filter should be a computed ref, following Vue's best practices for something like this

2024-05-30 16:24 UTC, MoShizzle commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +                .startsWith(searchedUserName.toLowerCase())
We should probably use .includes instead of startsWith

2024-05-30 16:24 UTC, MoShizzle commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +      <v-text-field hide-details single-line v-model="searchedUserName" />
Add the autofocus attribute to make the field focused once the menu opens

2024-05-30 17:51 UTC, codonade commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +          v-for="user in users.filter(
So, I should have something like `const searchedUsers = computed(() => users.filter)`, am I right?

2024-05-30 17:52 UTC, codonade commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +                .startsWith(searchedUserName.toLowerCase())
Oh yeah... Now I think about it I don't know why I chose `startsWith` in the first place 😅

2024-05-30 17:54 UTC, codonade commented on packages/frontend/src/components/common/inputs/BaseUserSelector.vue
> +      <v-text-field hide-details single-line v-model="searchedUserName" />
I spent a lot of time searching for something like this and couldn't find anything... Good to know this exists!

2024-05-30 17:56 UTC, codonade commented
Thanks for your comments, I'll try to tackle them as soon as possible. Also, sorry for the noob Vue mistakes, this is my first time dealing with it.

2024-05-30 18:08 UTC, codonade commented on packages/frontend/src/components/common/users/types.ts
> +export function getUserFullName(user: User): string {
Here, I didn't really understand where do you want me to put this function; I'm still trying to wrap my head around the architecture of the application so I don't particularly understand where stuff should be.

2024-06-01 09:52 UTC, MoShizzle commented on packages/frontend/src/components/common/users/types.ts
> +export function getUserFullName(user: User): string {
The useUsersService composable, you can find it under `compsables/services` directory

2024-06-01 16:02 UTC, MoShizzle approved these changes

2024-06-01 16:03 UTC, merged