Feature: Card Start Date
tillywork/tillywork pull request #70
Opened 2024-06-03 09:43 UTC by codonade

Set a starting date for a card along side its due date. Fixes #68

2024-06-03 10:54 UTC, codonade commented
Now, there are two main issues I know of: You can set `startsAt` to be after `dueAt` or vice versa, set `dueAt` to be before `startsAt`, and changes to fields don't sync between views until you refresh the application. Regarding the first issue, I didn't know where should I handle the validation; on the client or on the server?

2024-06-04 21:42 UTC, MoShizzle requested changes

2024-06-04 21:42 UTC, MoShizzle commented on packages/frontend/src/components/project-management/views/BaseView.vue
> +  {
Remove it from the views main page, only make it show on the BaseCard

2024-06-04 21:43 UTC, MoShizzle commented
> Now, there are two main issues I know of: You can set `startsAt` to be after `dueAt` or vice versa, set `dueAt` to be before `startsAt`, and changes to fields don't sync between views until you refresh the application. Regarding the first issue, I didn't know where should I handle the validation; on the client or on the server?

That's fine we don't have to handle it right now.

Regarding validation, usually you'd do both frontend and backend validation

2024-06-05 01:59 UTC, codonade commented on packages/frontend/src/components/project-management/views/BaseView.vue
> +  {
So, if I got you correctly, you want the start date property to only be visible when you specifically open the card, and not show it in other views?

2024-06-06 19:50 UTC, MoShizzle commented on packages/frontend/src/components/project-management/views/BaseView.vue
> +  {
Yes exactly

2024-06-07 07:17 UTC, codonade commented
Here it is, I reverted the repository status to when you could only edit the start date from the card view. I hope I haven't missed anything up with what I've did...

2024-06-07 07:51 UTC, MoShizzle requested changes

2024-06-07 07:51 UTC, MoShizzle commented on packages/frontend/src/components/project-management/cards/BaseCard.vue
> +          label="Due date"
This should be Start date

2024-06-07 11:03 UTC, MoShizzle approved these changes

2024-06-07 11:03 UTC, merged